### ISSUE TITLE
LoadError: ArgumentError: Color not found in path

### ISSUE THREAD

**Issue by sbromberger** [IainNZ/GraphLayout.jl#11]
I think this is a result of Tim's restructuring of Color.jl:

```
julia> using GraphLayout
ERROR: LoadError: LoadError: ArgumentError: Color not found in path
 in require at /usr/local/julia-latest/lib/julia/sys.dylib
 in include at /usr/local/julia-latest/lib/julia/sys.dylib
 in include_from_node1 at /usr/local/julia-latest/lib/julia/sys.dylib
 in include at /usr/local/julia-latest/lib/julia/sys.dylib
 in include_from_node1 at /usr/local/julia-latest/lib/julia/sys.dylib
 in require at /usr/local/julia-latest/lib/julia/sys.dylib
while loading /Users/seth/.julia/v0.4/GraphLayout/src/draw.jl, in expression starting on line 2
while loading /Users/seth/.julia/v0.4/GraphLayout/src/GraphLayout.jl, in expression starting on line 29
```

**Comment by IainNZ** [comment]
Ah yeah probably

**Comment by sbromberger** [comment]
Will try to fix it in the next few mins.

**Comment by sbromberger** [comment]
Yup, this isn't gonna be fixable until Compose.jl gets fixed, I think.

**Comment by sbromberger** [comment]
Ok, I'm thoroughly confused. I don't understand how pkg.julialang.org is showing passing tests (and how it's even loading `Colors.jl` as a dependency) when master has no reference to that package. What am I missing?

**Comment by IainNZ** [comment]
Isn't the on on pkg.julialang ancient?
`Current version: 0.2.0 (1 year, 1 month ago)`?

**Comment by IainNZ** [comment]
The tagged version doesn't even directly load Color/Colors, it just uses Compose. Master directly uses Color

**Comment by sbromberger** [comment]
Yes, but look at the test log:

```
INFO: Computing test dependencies for GraphLayout...
INFO: Installing ColorTypes v0.1.3
INFO: Installing Colors v0.5.2
```

How is it finding Colors 0.5.2?

**Comment by IainNZ** [comment]
https://github.com/JuliaLang/METADATA.jl/commit/1b03b7e0d9e00c31d71aeabf0f0763bbecbe77e8
?

**Comment by IainNZ** [comment]
I'm not seeing the problem

**Comment by sbromberger** [comment]
I guess Compose is requiring Colors, which explains how pkg.julialang.org is listing it as a dependency for 0.2.0, which makes no mention of it. OK. In any case, I've got my immediate issue fixed but tests aren't passing.

**Comment by IainNZ** [comment]
Latest tag for Compose requires Colors...?
https://github.com/dcjones/Compose.jl/commit/d87968b025980c3a299f619282a94a728f1869db
Why would GraphLayout 0.2 mention any kind of color package?

**Comment by sbromberger** [comment]
I don't know. I know that master requires a color package, and I guess I assumed (incorrectly) that 0.2 did as well. In any case, there's a testing error with latest master - I'll see what I can do.

**Comment by sbromberger** [comment]
Migrate discussion to #12.
