### ISSUE TITLE
Tree-like layout

### ISSUE THREAD

**Issue by dlfivefifty** [IainNZ/GraphLayout.jl#3]
I want to use this to construct a tree, like the default layout for TikzGraphs.

**Comment by jpfairbanks** [comment]
Can you give some more details about the layout? An example using TikzGraphs would be helpful.

**Comment by IainNZ** [comment]
I was thinking along these lines: http://en.wikipedia.org/wiki/Layered_graph_drawing

**Comment by jpfairbanks** [comment]
Can we call into Graphviz to get the coordinates? We want a native solution but it would be good to use an established library if it is easy enough.

**Comment by IainNZ** [comment]
The point of this project is to avoid GraphViz entirely, so I wouldn't want that code in here.

@jiahao @jakebolewski a fun use for JuMP, maybe: implementing one the integer programming formulations in this:
http://cs.brown.edu/~rt/gdhandbook/chapters/hierarchical.pdf

**Comment by jiahao** [comment]
cc @madeleineudell Is anyone at Stanford game to reformulate a hierarchical graph layout algorithm using a DCP instead of an integer program? ;-)

**Comment by madeleineudell** [comment]
You can actually do something like that with a simple recursion: does the following look like what you want?

![image](https://cloud.githubusercontent.com/assets/829940/7074952/396426e6-deb3-11e4-9b2f-510020248adc.png)

**Comment by jiahao** [comment]
I think so!

**Comment by IainNZ** [comment]
Yeah trees aren't so bad, I think the literature is mostly talking about visualizing DAGs (which are want I personally want)

**Comment by madeleineudell** [comment]
Suppose the graph is represented as a bunch of nodes:

type Node
  name::String
  children::Array{Node,1}
end

and we have a function width(s::String) that tells us how much space we
need to display that string.

We want to allocate to each node in the graph a column wide enough that all
of its children can be displayed in the column. (So the layout is
recursive.) Then the widths of the columns allocated to each node of the
tree I pasted in is produced by the following recursion on the graph:

width(node) = max(width(node.string), sum(map(width, node.children))

A node is displayed at the center of its allocated width.

I'm sure one could code this up in Compose without too much trouble...

On Thu, Apr 9, 2015 at 12:29 PM, Iain Dunning <notifications@github.com>
wrote:

> Yeah trees aren't so bad, I think the literature is mostly talking about
> visualizing DAGs (which are want I personally want)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IainNZ/GraphLayout.jl/issues/3#issuecomment-91334373>.
>



-- 
Madeleine Udell
PhD Candidate in Computational and Mathematical Engineering
Stanford University
www.stanford.edu/~udell

**Comment by IainNZ** [comment]
That'd definitely work for a tree, wouldn't you also need to do the height for a DAG though? I guess you can get a height by finding max distance from the root.

I think the literature I linked to is mostly on optimal layouts - i.e. avoiding crossings, which is apparently NP-hard (which matches my intuition).

**Comment by IainNZ** [comment]
This is partially addressed now by #10 but the graphical output sucks. I need to refactor the whole design, which I will do right now.

**Comment by IainNZ** [comment]
Current state of the tree layout and viz:
![Imgur](http://i.imgur.com/JPHvTSM.png)
