### ISSUE TITLE
weird (nondeterministic?) layouts

### ISSUE THREAD

**Issue by sbromberger** [IainNZ/GraphLayout.jl#4]
Sometimes I get proper layout:

```
g = WheelGraph(10); am = full(adjacency_matrix(g))   # boolean array
loc_x, loc_y = layout_spring_adj(am)
draw_layout_adj(am, loc_x, loc_y, filename="foo.svg")
```
![screen shot 2015-01-21 at 16 50 49](https://cloud.githubusercontent.com/assets/941359/5848475/b31c41f2-a18d-11e4-8a4d-fcd148335bc9.png)

Sometimes I get weird layout for the same graph when I repeat
```
loc_x, loc_y = layout_spring_adj(am)
draw_layout_adj(am, loc_x, loc_y, filename="foo.svg")
```

![screen shot 2015-01-21 at 16 54 14](https://cloud.githubusercontent.com/assets/941359/5848520/2b0ce126-a18e-11e4-8565-ff814854fb15.png)

(This is a 10-node wheel graph that was NOT regenerated prior to `loc_x, loc_y` calculations.)

Please let me know how I might begin to troubleshoot this, if in fact it represents a bug.

**Comment by IainNZ** [comment]
Nondeterministic, due to the random start:
https://github.com/IainNZ/GraphLayout.jl/blob/a0d36c4fef01936bf3cf69a9870636f5665e5359/src/spring.jl#L20-L22

Ideally there'd be some random restarting I guess, but always possible for it to go wrong due to the multiple local optima.

**Comment by IainNZ** [comment]
That first picture is a really cool looking though, I must say :D

**Comment by sbromberger** [comment]
Thanks for the quick response! Here's another one for you: if you look closely you can see the 3D dodecahedron :) (these are all in FastGraphs.jl, btw).

![screen shot 2015-01-21 at 17 06 46](https://cloud.githubusercontent.com/assets/941359/5848672/fc057922-a18f-11e4-9464-d104e17ab12d.png)

**Comment by sbromberger** [comment]
Closing out but feel free to reopen and I'll post some more cool graphs :)

**Comment by sbromberger** [comment]
One more:

![screen shot 2015-01-21 at 17 14 40](https://cloud.githubusercontent.com/assets/941359/5848761/0a67faca-a191-11e4-8d27-03bb6d3f1622.png)
