### ISSUE TITLE
Pass colors as arguments to draw_layout_adj

### ISSUE THREAD

**Issue by jpfairbanks** [IainNZ/GraphLayout.jl#5]
It looks like this package could support drawing graphs with color using this modification:
The current code has the colors as literals.
~~~~julia
draw(   filename == "" ? SVG(4inch, 4inch) : SVG(filename, 4inch, 4inch),  
            compose(
                context(units=UnitBox(-1.2,-1.2,+2.4,+2.4)),
                compose(context(), texts..., fill("#000000"), stroke(nothing), fontsize(4.0)),
                compose(context(), nodes..., fill("#AAAAFF"), stroke("#BBBBBB")),
                compose(context(), lines..., stroke("#BBBBBB"), linewidth(LINEWIDTH))
            )
        )
~~~~
using the arguments `labelc, nodefillc, nodestrokec, edgestrokec` for the colors

we need to change the function signature to
~~~~julia
function draw_layout_adj{S, T<:Real}(
    adj_matrix::Array{S,2}, 
    locs_x::Vector{T}, locs_y::Vector{T};
    labels::Vector={},
    filename::String="",
    labelc::String="#000000",
    nodefillc::String="#AAAAFF",
    nodestrokec::String="#BBBBBB",
    edgestrokec::String="#BBBBBB")
~~~~

and the drawing code itself becomes:
~~~~julia
draw(   filename == "" ? SVG(4inch, 4inch) : SVG(filename, 4inch, 4inch),  
            compose(
                context(units=UnitBox(-1.2,-1.2,+2.4,+2.4)),
                compose(context(), texts..., fill(labelc), stroke(nothing), fontsize(4.0)),
                compose(context(), nodes..., fill(nodefillc), stroke(nodestrokec)),
                compose(context(), lines..., stroke(edgestrokec), linewidth(LINEWIDTH))
            )
        )
~~~~

Are there any ramifications to changing this? Are these good argument names? While making this change should we also allow the fontsize to be passed as an argument too?

**Comment by jpfairbanks** [comment]
Actually I realized this doesn't solve my problem because I want to associate a different color to each vertex based on some computation.

**Comment by IainNZ** [comment]
Yeah you'd need to modify the code a bit more do to that. Its a good feature though, so feel free to submit a PR!

**Comment by IainNZ** [comment]
Wait, can I close this?

**Comment by jpfairbanks** [comment]
Yes you can close it. I will open another issue for the feature request of individual colors per vertex.
