### ISSUE TITLE
Assign each vertex and edge a color

### ISSUE THREAD

**Issue by jpfairbanks** [IainNZ/GraphLayout.jl#9]
A common use case of mine is to color vertices in a graph based on some property.
The API change necessary is for each color option of the `draw` function, we should accept an `AbstractArray{ComposeColor}` of the appropriate length. 

The current code could be modified so that if any color option is given with type `ComposeColor`, we broadcast that up to an array of the appropriate length.

**Comment by IainNZ** [comment]
That seems reasonable

**Comment by leethargo** [comment]
:+1: 

@jpfairbanks, do you already have some code for this? Otherwise I might give it a try this weekend.

**Comment by jpfairbanks** [comment]
I don't or can't find it :disappointed:.

I remember thinking about it.
You should only need to accept nodestrokec as a Vector{ComposeColor} and then change this part to iterate over nodes.
draw.jl L77
```julia 
    # Create labels (if wanted)
    texts = length(labels) == N ?
        [text(locs_x[i],locs_y[i],labels[i],hcenter,vcenter) for i=1:N] : Any[]

    compose(context(units=UnitBox(-1.2,-1.2,+2.4,+2.4)),
        compose(context(), texts..., fill(labelc), stroke(nothing), fontsize(labelsize)),
        compose(context(), nodes..., fill(nodefillc), stroke(nodestrokec)),
        compose(context(), lines..., stroke(edgestrokec), linewidth(LINEWIDTH))
    )
```

**Comment by leethargo** [comment]
OK, thanks.
